//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQBuildingCount
    {
        public int ACQBuildingCountId { get; set; }
        public int ACQGameId { get; set; }
        public int ACQHotelChainId { get; set; }
        public int BuildingCount { get; set; }
    
        public virtual ACQGame ACQGame { get; set; }
        public virtual ACQHotelChain ACQHotelChain { get; set; }
    }
}
