//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACQGame()
        {
            this.ACQBuildingCounts = new HashSet<ACQBuildingCount>();
            this.ACQPlayers = new HashSet<ACQPlayer>();
        }
    
        public int ACQGameId { get; set; }
        public string GameName { get; set; }
        public System.DateTime GameStart { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQBuildingCount> ACQBuildingCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQPlayer> ACQPlayers { get; set; }
    }
}
