//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQHotelChain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACQHotelChain()
        {
            this.ACQBuildingCounts = new HashSet<ACQBuildingCount>();
            this.ACQPlayerStocks = new HashSet<ACQPlayerStock>();
            this.ACQStockholderInfoes = new HashSet<ACQStockholderInfo>();
        }
    
        public int ACQHotelChainId { get; set; }
        public string HotelChainName { get; set; }
        public string HotelChainColor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQBuildingCount> ACQBuildingCounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQPlayerStock> ACQPlayerStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQStockholderInfo> ACQStockholderInfoes { get; set; }
    }
}
