//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQPlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACQPlayer()
        {
            this.ACQPlayerStocks = new HashSet<ACQPlayerStock>();
        }
    
        public int ACQPlayerId { get; set; }
        public int ACQGameId { get; set; }
        public string PlayerName { get; set; }
    
        public virtual ACQGame ACQGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACQPlayerStock> ACQPlayerStocks { get; set; }
    }
}
