//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQPlayerStock
    {
        public int ACQPlayerStockId { get; set; }
        public int ACQPlayerId { get; set; }
        public int ACQHotelChainId { get; set; }
        public int StockCount { get; set; }
    
        public virtual ACQHotelChain ACQHotelChain { get; set; }
        public virtual ACQPlayer ACQPlayer { get; set; }
    }
}
