//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACQStockholderInfo
    {
        public int ACQStockholderInfoId { get; set; }
        public int ACQHotelChainId { get; set; }
        public int SizeFrom { get; set; }
        public int SizeTo { get; set; }
        public int StockPrice { get; set; }
        public int PrimaryHolder { get; set; }
        public int SecondaryHolder { get; set; }
        public int TertiaryHolder { get; set; }
        public string ACQGameMode { get; set; }
    
        public virtual ACQHotelChain ACQHotelChain { get; set; }
    }
}
