//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApps
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoAppEntities : DbContext
    {
        public DemoAppEntities()
            : base("name=DemoAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACQBuildingCount> ACQBuildingCounts { get; set; }
        public virtual DbSet<ACQGame> ACQGames { get; set; }
        public virtual DbSet<ACQGameMode> ACQGameModes { get; set; }
        public virtual DbSet<ACQHotelChain> ACQHotelChains { get; set; }
        public virtual DbSet<ACQPlayer> ACQPlayers { get; set; }
        public virtual DbSet<ACQPlayerStock> ACQPlayerStocks { get; set; }
        public virtual DbSet<ACQStockholderInfo> ACQStockholderInfoes { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
    }
}
